# NumPY

In [1]:
import  numpy as np          #np as aLias of numpy

In [11]:
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in array

In [17]:
arr=np.array((2))
print(type(arr))
print(arr)
print(arr.ndim)

<class 'numpy.ndarray'>
2
0


# 1 D array

In [23]:
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [26]:
arr= np.array([[1,2,3,4,5],[3,54,6,2,1]])
print(arr)
print("the size of array is",arr.ndim)

[[ 1  2  3  4  5]
 [ 3 54  6  2  1]]
the size of array is 2


# 3 D array

In [30]:
arr= np.array([[[1,2,43,2,1],[5,3,2,1,3],[3,2,5,4,1]]])
print(arr)
print(arr.ndim)

[[[ 1  2 43  2  1]
  [ 5  3  2  1  3]
  [ 3  2  5  4  1]]]
3


## TO CHECK THE DIMENSIONS OF ARRAY U HAVE TO CHECK THE AST SQUARE BRACKETS 
### no of brackets= the dimension no

# creating the 5 d array 

In [34]:
arr= np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [36]:
arr= np.array([[[[[1,2,3,4]]]]])
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


# indexing

In [44]:
arr= np.array([12,3,2,5])
print(arr[0])
print(arr[3])
print("the sum of above two is",arr[0]+arr[3])

12
5
the sum of above two is 17


# accessing from 2d array

In [57]:
arr= np.array([[1,3,2,54],[2,5,3,9]])
print(arr)
a= arr[0,1]
b=arr[1,3]
print("2nd eLement on 1st row is:", arr[0,1])
print("4th eLement on 2nd row:",arr[1,3])
print("sum is:",arr[0,1]+arr[1,3])
print("sum of above is:",(a+b))

[[ 1  3  2 54]
 [ 2  5  3  9]]
2nd eLement on 1st row is: 3
4th eLement on 2nd row: 9
sum is: 12
sum of above is: 12


## accesing 3d array

In [65]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr[0,0,0])
print(arr[0,1,0])
print(arr[0,2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
4
9


# NumPY part 2

# SLICING

In [66]:
arr= np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


In [69]:
arr= np.array([1,3,4,5,7])
print(arr[::2])

[1 4 7]


# in 2 d array 

In [74]:
arr= np.array([[1,3,2,5],[4,8,5,2]])
print(arr[1,1:3])
print(arr[0,1:3])

[8 5]
[3 2]


# checking the data type of an array 

In [75]:
a=np.array([1,4,3])
print(a.dtype)

int32


In [77]:
a=np.array(["animaLs","bat","cat","dog"])
print(a.dtype)

<U7


# Creating array with a defined data type

In [78]:
arr= np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [79]:
arr= np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# NumPY array shape

the shape of an array is the number of eLements in each dimension


print the shape of 2d array

# shape means the rows and coLoumns in array

In [82]:
arr=np.array([[1,2,3,4],[5,6,3,4]])
print(arr.shape)

(2, 4)


In [83]:
arr= np.array([[[1,2,3],[65,3,1],[4,1,8]]])
print(arr.shape)

(1, 3, 3)


# Joining numpy arrays

In [90]:
arr1= np.array([1,2,3])

arr2= np.array([6,9,7])
print(arr1)
print(arr2)

arr= np.concatenate((arr2,arr1))
arr3= np.concatenate((arr1,arr2))
print(arr)
print(arr3)

[1 2 3]
[6 9 7]
[6 9 7 1 2 3]
[1 2 3 6 9 7]


# join 2 d array

# axis=1 , means rows
# axis=0, means coLumns

In [101]:
arr1= np.array([[1,3],[5,4]])
arr2= np.array([[8,9],[6,7]])
arr= np.concatenate((arr1,arr2), axis=1)
print("aLong axis 1 , row wise:\n",arr)
print("-------------------------")
a= np.concatenate((arr1,arr2), axis=0)
print("aLong axis=0 meanscoLoumn wise:\n",a)

aLong axis 1 , row wise:
 [[1 3 8 9]
 [5 4 6 7]]
-------------------------
aLong axis=0 meanscoLoumn wise:
 [[1 3]
 [5 4]
 [8 9]
 [6 7]]


# spLitting numpy array

# spLitting the array in 3 parts

In [113]:
arr= np.array([1,4,3,5,6,78,3,4])
a= np.array_split(arr,3)
print(a)
b= np.array_split(arr,2)
print(b)

[array([1, 4, 3]), array([ 5,  6, 78]), array([3, 4])]
[array([1, 4, 3, 5]), array([ 6, 78,  3,  4])]


# raveL and fLatten 

In [118]:
a= np.array([[[1,2],[3,4],[5,6]]])
print(a)
print("dimension of a is:",a.ndim)
r= a.ravel()
print(r)
print(r.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
dimension of a is: 3
[1 2 3 4 5 6]
1


In [120]:
a= np.array([[[1,2],[3,4],[5,6]]])
print(a)
print("dimension of a is:",a.ndim)
r= a.flatten()
print(r)
print(r.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
dimension of a is: 3
[1 2 3 4 5 6]
1


# unique function

In [125]:
k=np.array([1,2,3,6,3,2,12,3,4,56,7,6,54,21,2,4,1,3,4,3,56,7,7,8,3,1,23,4,5,3,67,1])
print(k)
x=np.unique(k)
print("unique no's are :",x)

[ 1  2  3  6  3  2 12  3  4 56  7  6 54 21  2  4  1  3  4  3 56  7  7  8
  3  1 23  4  5  3 67  1]
unique no's are : [ 1  2  3  4  5  6  7  8 12 21 23 54 56 67]


In [142]:
k=np.array([1,2,3,6,3,2,12,3,4,56,7,6,54,21,2,4,1,3,4,3,56,7,7,8,3,1,23,4,5,3,67,1])
print(k)
x=np.unique(k , return_index= True)
print("unique no's are :",x)

[ 1  2  3  6  3  2 12  3  4 56  7  6 54 21  2  4  1  3  4  3 56  7  7  8
  3  1 23  4  5  3 67  1]
unique no's are : (array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 21, 23, 54, 56, 67]), array([ 0,  1,  2,  8, 28,  3, 10, 23,  6, 13, 26, 12,  9, 30],
      dtype=int64))


In [144]:
k=np.array([1,2,3,6,3,2,12,3,4,56,7,6,54,21,2,4,1,3,4,3,56,7,7,8,3,1,23,4,5,3,67,1])
print(k)
x=np.unique(k , return_index= True, return_counts=True)
print("unique no's are :",x)

[ 1  2  3  6  3  2 12  3  4 56  7  6 54 21  2  4  1  3  4  3 56  7  7  8
  3  1 23  4  5  3 67  1]
unique no's are : (array([ 1,  2,  3,  4,  5,  6,  7,  8, 12, 21, 23, 54, 56, 67]), array([ 0,  1,  2,  8, 28,  3, 10, 23,  6, 13, 26, 12,  9, 30],
      dtype=int64), array([4, 3, 7, 4, 1, 2, 3, 1, 1, 1, 1, 1, 2, 1], dtype=int64))


# Delete 

In [147]:
a= np.array([1,2,3,4,5])
print(a)
d= np.delete(a,[2])
print("deleted array:",d)

[1 2 3 4 5]
deleted array: [1 2 4 5]


In [150]:
x= np.array([[2,6,3,2],[1,6,7,8],[3,5,4,2]])
print(x)
print()
s= np.delete(x,1,axis=0)
print(s)


[[2 6 3 2]
 [1 6 7 8]
 [3 5 4 2]]

[[2 6 3 2]
 [3 5 4 2]]
